#!/bin/bash
# Create a GitHub issue for a completed video enhancement
#
# Usage: ./create_issue.sh <video_id> <title> <scale> [status]
#
# Example: ./create_issue.sh JXir0H9XPzY "009 ChickenPick" 4 completed

set -e

VID="${1:?Usage: ./create_issue.sh <video_id> <title> <scale> [status]}"
TITLE="${2:?Missing title}"
SCALE="${3:?Missing scale (2 or 4)}"
STATUS="${4:-completed}"

YT_URL="https://www.youtube.com/watch?v=$VID"

ISSUE_TITLE="[${STATUS}] ${TITLE} (${SCALE}x upscale)"

BODY="$(cat <<EOF
## Video Enhancement: ${TITLE}

| Field | Value |
|-------|-------|
| **Original** | [${YT_URL}](${YT_URL}) |
| **Video ID** | \`${VID}\` |
| **Scale** | ${SCALE}x |
| **Status** | ${STATUS} |
| **Model** | Real-ESRGAN x4plus |
| **Date** | $(date +%Y-%m-%d) |

### Checklist
- [ ] Quality reviewed
- [ ] Uploaded to YouTube as "${TITLE} (Enhanced 4K)"
- [ ] Old video deleted from YouTube

---
Generated by old2new
EOF
)"

# Check if issue already exists
EXISTING=$(gh issue list --repo zdavatz/old2new --search "\"${TITLE}\" in:title" --json number --jq '.[0].number' 2>/dev/null)

if [ -n "$EXISTING" ]; then
    echo "Issue #$EXISTING already exists for '${TITLE}'. Updating..."
    gh issue edit "$EXISTING" --repo zdavatz/old2new --title "$ISSUE_TITLE" --body "$BODY"
    echo "Updated: https://github.com/zdavatz/old2new/issues/$EXISTING"
else
    gh issue create --repo zdavatz/old2new --title "$ISSUE_TITLE" --body "$BODY"
fi
